### ISSUE TITLE
action

### ISSUE THREAD

**Issue by RAIDZA** [reybahl/Assistant#1]
Good Day

I get an action is undefined?? please can you explain #newbie

**Comment by reybahl** [comment]
@RAIDZA, can you please share the part of the code that is causing this error?

**Comment by RAIDZA** [comment]
try: #Tries terminating an action if it exists
                    action.terminate()
                except:
                    pass

**Comment by RAIDZA** [comment]
Thank you for your quick response by the way.

**Comment by RAIDZA** [comment]
``            keyword_index = self.porcupine.process(pcm)

            if keyword_index >= 0:
                print("Hotword Detected")
                
                try: #Tries terminating an action if it exists
                    action.terminate()
                except:
                    pass

**Comment by reybahl** [comment]
That shouldn't be causing an error, but try removing the `try` ... `except` and all the code inside it.

**Comment by RAIDZA** [comment]
will do. Will update a bit later thank you

**Comment by RAIDZA** [comment]
Just checking out the code, action is not assigned to anything its #out

**Comment by reybahl** [comment]
Yeah, it's not assigned to anything. It's there because I initially wanted to use multiprocessing, but I later decided not to. I forgot to remove this code, however.

Thanks for pointing that out.
