### ISSUE TITLE
FileNotFound Error: No such file found as weathertoken.txt

### ISSUE THREAD

**Issue by THAMIZH-ARASU** [reybahl/Assistant#3]
Please give the weather.txt file 

the interpreter is showing error for me...

Please help fix this problem

**Comment by reybahl** [comment]
Hello @THAMIZH-ARASU, this is an API key that I have kept private. To use the weather feature, you will need to get a key from https://openweathermap.org/api (there is a free version) and store it in the file `weathertoken.txt`.

**Comment by THAMIZH-ARASU** [comment]
@reybahl 
Thank you for the quick response ...❤️
I will give it a try

**Comment by reybahl** [comment]
[I added weather instructions to the repository](https://github.com/reybahl/Assistant/commit/2dda273bd18c90d8889ed8352d221ed73f10d6fb). I will now be closing this issue; feel free to reopen it if you are having issues.
