### ISSUE TITLE
ModuleNotFoundError: No module named 'assistant_functions'

### ISSUE THREAD

**Issue by avgeek132638** [reybahl/Assistant#4]
i keep on getting this error when trying to run anything on the file

**Comment by reybahl** [comment]
@avgeek132638 this error occurs when you run a file outside the root directory. Try running main.py from the project's root directory.

**Comment by reybahl** [comment]
[2dda273](https://github.com/reybahl/Assistant/commit/2dda273bd18c90d8889ed8352d221ed73f10d6fb)
